version: '2'
services:
    couchdb:
      image: couchdb:1.6.1
    test:
      image: acroyear2/alpine-node:8.4.0
      links:
        - "couchdb"
      depends_on:
        - couchdb
      volumes:
        - .:/build
